# -*- coding: utf-8 -*-
"""csi_recorder_u14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBtVFOWqvHfViysBwrPC862GwWvPcINi
"""

import os
import time
import subprocess
import signal
from datetime import datetime

# --- 配置區 ---
# 這裡填入你照片中看到的相對路徑
RELATIVE_PATH = "linux-80211n-csitool-supplementary/netlink/log_to_file"
TOTAL_RUNTIME_MIN = 20  # 總共跑 20 分鐘
SEGMENT_MIN = 5        # 每 5 分鐘切一個檔
SAVE_DIR = "csi_breathe_data"

# 自動轉換為絕對路徑 (解決 command not found)
CSI_TOOL_PATH = os.path.abspath(RELATIVE_PATH)

def run_experiment():
    # 1. 檢查執行檔是否存在
    if not os.path.exists(CSI_TOOL_PATH):
        print("錯誤：找不到執行檔！")
        print("請確認你目前在 Terminal 的位置可以看到 {0}".format(RELATIVE_PATH))
        return

    if not os.path.exists(SAVE_DIR):
        os.makedirs(SAVE_DIR)

    total_sec = TOTAL_RUNTIME_MIN * 60
    segment_sec = SEGMENT_MIN * 60
    global_start = time.time()
    file_count = 1

    print("=== 啟動呼吸採集任務 (Ubuntu 14) ===")
    print("工具路徑: {0}".format(CSI_TOOL_PATH))
    print("預計總時長: {0} 分鐘".format(TOTAL_RUNTIME_MIN))

    try:
        while (time.time() - global_start) < total_sec:
            # 產出帶時間戳記的檔案
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = os.path.join(SAVE_DIR, "real_breathe_{0}_seg{1}.dat".format(timestamp, file_count))

            # 核心指令：由 Python 幫你下 sudo 執行指令
            cmd = ["sudo", CSI_TOOL_PATH, filename]

            print("[{0}] 第 {1} 段開始錄製...".format(datetime.now().strftime('%H:%M:%S'), file_count))

            # 背景執行 C 程式
            process = subprocess.Popen(cmd)

            # 等待分段時間（5 分鐘）
            start_wait = time.time()
            while (time.time() - start_wait) < segment_sec:
                if (time.time() - global_start) >= total_sec:
                    break
                time.sleep(1)

            # 重要：自動發送中斷訊號 (Ctrl+C) 確保數據正確寫入 .dat 檔案
            os.kill(process.pid, signal.SIGINT)
            process.wait()

            print(">> 第 {0} 段儲存成功: {1}".format(file_count, os.path.basename(filename)))
            file_count += 1

        print("\n=== [完成] 20 分鐘實驗成功結束 ===")

    except KeyboardInterrupt:
        print("\n[手動終止] 正在關閉採集程式...")
        if 'process' in locals():
            os.kill(process.pid, signal.SIGINT)

if __name__ == "__main__":
    run_experiment()